log_sources:
  linux_secure: /var/log/secure # or auth.log depending on your system
  windows_evtx: your\log\location
  firewall_log: c:logs\firewall.log

slack_webhook_url: "your/slack/url/for/notificatoin"